import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [data, setData] = useState()
  
  const onGetUser = async () => {
    const res = await axios.get('https://api.charisman-afriandi.com/user')
    const {data} = res

    setData(res.data)
    console.log('success get user');
  }

  const onGetProject = async () => {
    const res = await axios.get('https://api.charisman-afriandi.com/project')
    const {data} = res

    setData(res.data)
    console.log('success get project');
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Test to deploy my Next app on <a href="#">Cpanel!</a>
        </h1>

        <button onClick={() => onGetUser()}>get user</button>
        <button onClick={() => onGetProject()}>get project</button>
        
        <p className={styles.description}>
          <code className={styles.code}>{data && data.map(item => (
            <p key={item.id}>{item.name}</p>
          ))}</code>
        </p>

      </main>
    </div>
  )
}
